// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFA6ccKQSHjt35ajFsVMXH0LegWgPCfaU',
    appId: '1:1031528374971:web:95fd2bebb080ed07123f9e',
    messagingSenderId: '1031528374971',
    projectId: 'protrade-app',
    authDomain: 'protrade-app.firebaseapp.com',
    storageBucket: 'protrade-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtERmLkJ8bpsWlQ-GXV7S71knqlxAAVs',
    appId: '1:1031528374971:android:cc685731cf3ee381123f9e',
    messagingSenderId: '1031528374971',
    projectId: 'protrade-app',
    storageBucket: 'protrade-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9s2lTG6R3oM8cQXhFHIs56Azja_i_BZA',
    appId: '1:1031528374971:ios:ff468c33294e35f2123f9e',
    messagingSenderId: '1031528374971',
    projectId: 'protrade-app',
    storageBucket: 'protrade-app.firebasestorage.app',
    iosBundleId: 'com.example.protradeHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9s2lTG6R3oM8cQXhFHIs56Azja_i_BZA',
    appId: '1:1031528374971:ios:ff468c33294e35f2123f9e',
    messagingSenderId: '1031528374971',
    projectId: 'protrade-app',
    storageBucket: 'protrade-app.firebasestorage.app',
    iosBundleId: 'com.example.protradeHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFA6ccKQSHjt35ajFsVMXH0LegWgPCfaU',
    appId: '1:1031528374971:web:3c60ee2c5565c2d2123f9e',
    messagingSenderId: '1031528374971',
    projectId: 'protrade-app',
    authDomain: 'protrade-app.firebaseapp.com',
    storageBucket: 'protrade-app.firebasestorage.app',
  );
}
